AWSTemplateFormatVersion: '2010-09-09'
Description: 'Template CloudFormation FGC - EKS'

Parameters:
  ClusterRoleArn:
    Type: String
    Description: 'ARN da IAM Role existente para o EKS Cluster (ex: LabRole da AWS Academy)'

  NodeRoleArn:
    Type: String
    Description: 'ARN da IAM Role existente para os Worker Nodes (ex: LabRole da AWS Academy)'

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: 'Lista de IDs de pelo menos 2 Subnets (em zonas de disponibilidade diferentes)'

Resources:
  EKSCluster:
    Type: AWS::EKS::Cluster
    Properties:
      Name: "fgc"
      RoleArn: !Ref ClusterRoleArn
      ResourcesVpcConfig:
        SubnetIds: !Ref SubnetIds
        EndpointPublicAccess: true
        EndpointPrivateAccess: true

  EKSNodes:
    Type: AWS::EKS::Nodegroup
    Properties:
      ClusterName: !Ref EKSCluster
      NodegroupName: fgc-nodegroup
      NodeRole: !Ref NodeRoleArn
      Subnets: !Ref SubnetIds
      InstanceTypes:
        - t3.medium
      ScalingConfig:
        MinSize: 1
        DesiredSize: 2
        MaxSize: 3
      DiskSize: 20
      AmiType: AL2_x86_64

Outputs:
  ClusterEndpoint:
    Description: 'Endpoint da API do EKS'
    Value: !GetAtt EKSCluster.Endpoint
    Export:
      Name: !Sub fgc-endpoint

  ClusterNameOutput:
    Description: 'Nome do Cluster EKS criado'
    Value: !Ref EKSCluster
    Export:
      Name: !Sub fgc-name