{
 "title": "FGC",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "app", "label": "Microsserviço", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  { "title": "Métricas das requisições", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Contagem  Total de Requisições",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(app, code) (increase(http_requests_received_total{job=\"kubernetes-pods\", app=~\"$app\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Contagem Total de Requisições (por status code)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(method, path, code) (rate(http_requests_received_total{app=~\"$app\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Taxa de Erros (Error Rate - HTTP 5xx e 4xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by(code) (rate(http_requests_received_total{app=~\"$app\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latência de Requisições (Tempo de Resposta - p95 e p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(http_request_duration_seconds_bucket{job=\"kubernetes-pods\", app=~\"$app\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}